### ISSUE TITLE
Can one run `fal test`?

### ISSUE THREAD

**Issue by CavalcanteLucas** [fal-ai/fal_dbt_examples#18] opened 2023-03-22 18:16 UTC
I'm trying to make something like this:

```
fal test --profiles-dir . --target dev --selector my_data --vars '{my_var: "my_var_value"}'
```

Is it currently supported?

**Comment by chamini2** [comment] 2023-03-28 00:12
This is a duplicate of https://github.com/fal-ai/fal/issues/792

**Closed as completed by chamini2** 2023-03-28 00:12 UTC
